name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Release
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: true
          prerelease: false
          draft: false
          name-template: 'v$RESOLVED_VERSION'
          tag-template: 'v$RESOLVED_VERSION'
          categories:
            - title: '🚀 Features'
              labels:
                - 'feat'
                - 'enhancement'
            - title: '🐛 Bug Fixes'
              labels:
                - 'fix'
                - 'bugfix'
                - 'bug'
            - title: '🧰 Maintenance'
              labels:
                - 'chore'
                - 'documentation'
                - 'ci'
                - 'build'
                - 'perf'
                - 'refactor'
                - 'style'
                - 'test'
            - title: '📦 Dependencies'
              labels:
                - 'dependencies'
                - 'deps' 